config/routes.rb
LearningLog::Application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"} do
     get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
     get 'sign_out' => 'devise/sessions#destroy'
     get '/users/sign_in' => 'devise/sessions#new'
     get '/users/sign_up', :to => redirect('/users/auth/google_apps')
   end

  resources :logs

  root :to => "logs#index"
  

end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  include Gravtastic
  gravtastic
  
  
  def self.find_for_google_apps_oauth(access_token, signed_in_resource=nil)        
      data = access_token['user_info']
      email = data['email']      
      if user = User.find_by_email(email)
        user
      else
        User.create!(:email => email, :password => Devise.friendly_token[0,20])
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
 before_filter :authenticate_user!
 
  def index
    @logs = Log.find_all_by_user_id(current_user.id)
  
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @logs }
    end
  end 
  
  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @log }
    end
  end

  def new
    @log = Log.new
    @users = User.all
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @log }
    end
  end


  def edit
    @log = Log.find(params[:id])
    @users = User.all
  end

  def create

    @log = Log.new(params[:log])
    @log.user_id = current_user.id
    
    respond_to do |format|
      if @log.save
        format.html { redirect_to(@log, :notice => 'Log was successfully created.') }
        format.xml  { render :xml => @log, :status => :created, :location => @log }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @log.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @log = Log.find(params[:id])
    @log.user_id = current_user.id
    
    respond_to do |format|
      if @log.update_attributes(params[:log])
        format.html { redirect_to(@log, :notice => 'Log was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @log.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @log = Log.find(params[:id])
    @log.destroy

    respond_to do |format|
      format.html { redirect_to(logs_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_apps
    omniauth = env["omniauth.auth"]
    
    @user = User.find_for_google_apps_oauth(omniauth, current_user)
    
    if @user and @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:alert] = I18n.t "devise.omniauth_callbacks.failure"
      redirect_to root_url
    end
  end
  
  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title LearningLog
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = stylesheet_link_tag 'application.css', :media => 'screen, projection'
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'print.css', :media => 'print'		
    /[if lt IE 8]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'
  %body
    %div#topo
	
    %div.span-24.last#home
      - if user_signed_in?
        = image_tag current_user.gravatar_url
        %br/
        = current_user.try(:email)
        \ 
        \#{link_to '(Sair)', "/users/sign_out"}
      = yield

    %div#rodape

app/views/logs/_form.html.haml
= form_for(@log) do |f|
  - if @log.errors.any?
    #error_explanation
      %h2
        = pluralize(@log.errors.count, "error")
        prohibited this log from being saved:
      %ul
        - @log.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :description
    %br/
    = f.text_field :description
  .field
    = f.label :created_at
    %br/
    = @log.created_at
  .field
    = f.label :text
    %br/
    = f.text_area :text
  .actions
    = f.submit

app/views/logs/edit.html.haml
%h1 Editing log
= render 'form' 
= link_to 'Show', @log  |
= link_to 'Back', logs_path

app/views/logs/index.html.haml
%h1{:style => "color:darkblue"} Lista de Logs
%table
  %br/
  %thead
    %tr
      %th= t(:date)
      %th= t(:description)
      %th{:colspan => "3"}
  %tbody
    - @logs.each do |log|
      <tr class=#{cycle('even', 'odd')}>
      %td= log.created_at.to_formatted_s(:long)
      %td= log.description
      %td= link_to 'Visualizar', log, :class =>"button"
      %td= link_to 'Editar', edit_log_path(log), :class =>"button"
      %td= link_to 'Excluir', log, :confirm => 'Confirma exclusão?', :method => :delete, :class =>"button danger"
%br/
= link_to 'Novo Log', new_log_path, :class =>"button primary"

app/views/logs/new.html.haml
%h1 New log
= render 'form' 
= link_to 'Back', logs_path 

app/views/logs/show.html.haml
%p#notice= notice
%p
  %b usuário:
  = @log.user.email
%p
  %b Título:
  = @log.description
%p
  %b Descrição:
  = @log.text
%table
  %tr
    %td= link_to 'Voltar', logs_path, :class =>"button"
    %td= link_to 'Editar', edit_log_path(@log), :class =>"button"